import numpy as np

def write_xyz_file(xyz_data, file_name):
    # write the array to a file in XYZ format
    with open(file_name, "w") as f:
        # write the number of atoms as the first line
        f.write(str(xyz_data.shape[0]) + "\n")
        # write a comment line as the second line (can be any string)
        f.write("Generated by MolDyML\n")
        # write the coordinates of each atom
        np.savetxt(f, xyz_data, fmt="%10.5f", delimiter="   ")


# Given a list of important indexes, parse an extended xyz file 
import numpy as np

def extract_configurations(xyz_file, indexes_of_interest, output_file=None):
        # read in the contents of the XYZ file
        with open(xyz_file, "r") as f:
            lines = f.readlines()

        # extract the number of atoms from the first line of the file
        n_atoms = int(lines[0])

        # split the file into separate configurations
        configurations = []
        for i in range(0, len(lines), n_atoms + 2):
            configuration = lines[i:i+n_atoms+2]
            configurations.append(configuration)

        # extract the configurations with the desired indexes
        output_configurations = []
        for n, configuration in enumerate(configurations):
            if n in indexes_of_interest:
                output_configurations.append(configuration)

        # write the output configurations to a new XYZ file

        if output_file is None:
            output_file=xyz_file.replace('.xyz','_extracted.xyz')
        with open(output_file, "w") as f:
            for configuration in output_configurations:
                f.writelines(configuration)

